=begin
#World News API

#The world's news wrapped into a single API.

The version of the OpenAPI document: 2.2.0
Contact: mail@worldnewsapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'cgi'

module OpenapiClient
  class NewsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Extract News
    # Extract a news article from a website to a well structure JSON object. The API will return the title, text, URL, images, videos, publish date, authors, language, source country, and sentiment of the news article.
    # @param url [String] The url of the news.
    # @param [Hash] opts the optional parameters
    # @option opts [Boolean] :analyze Whether to analyze the extracted news (extract entities, detect sentiment etc.)
    # @return [ExtractNews200Response]
    def extract_news(url, opts = {})
      data, _status_code, _headers = extract_news_with_http_info(url, opts)
      data
    end

    # Extract News
    # Extract a news article from a website to a well structure JSON object. The API will return the title, text, URL, images, videos, publish date, authors, language, source country, and sentiment of the news article.
    # @param url [String] The url of the news.
    # @param [Hash] opts the optional parameters
    # @option opts [Boolean] :analyze Whether to analyze the extracted news (extract entities, detect sentiment etc.)
    # @return [Array<(ExtractNews200Response, Integer, Hash)>] ExtractNews200Response data, response status code and response headers
    def extract_news_with_http_info(url, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.extract_news ...'
      end
      # verify the required parameter 'url' is set
      if @api_client.config.client_side_validation && url.nil?
        fail ArgumentError, "Missing the required parameter 'url' when calling NewsApi.extract_news"
      end
      if @api_client.config.client_side_validation && url.to_s.length > 1000
        fail ArgumentError, 'invalid value for "url" when calling NewsApi.extract_news, the character length must be smaller than or equal to 1000.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && url !~ pattern
        fail ArgumentError, "invalid value for 'url' when calling NewsApi.extract_news, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/extract-news'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'url'] = url
      query_params[:'analyze'] = opts[:'analyze'] if !opts[:'analyze'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ExtractNews200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.extract_news",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#extract_news\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Extract News Links
    # Extract news links from a news website.
    # @param url [String] The url of the news.
    # @param [Hash] opts the optional parameters
    # @option opts [Boolean] :analyze Whether to analyze the extracted news (extract entities, detect sentiment etc.)
    # @return [ExtractNewsLinks200Response]
    def extract_news_links(url, opts = {})
      data, _status_code, _headers = extract_news_links_with_http_info(url, opts)
      data
    end

    # Extract News Links
    # Extract news links from a news website.
    # @param url [String] The url of the news.
    # @param [Hash] opts the optional parameters
    # @option opts [Boolean] :analyze Whether to analyze the extracted news (extract entities, detect sentiment etc.)
    # @return [Array<(ExtractNewsLinks200Response, Integer, Hash)>] ExtractNewsLinks200Response data, response status code and response headers
    def extract_news_links_with_http_info(url, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.extract_news_links ...'
      end
      # verify the required parameter 'url' is set
      if @api_client.config.client_side_validation && url.nil?
        fail ArgumentError, "Missing the required parameter 'url' when calling NewsApi.extract_news_links"
      end
      if @api_client.config.client_side_validation && url.to_s.length > 1000
        fail ArgumentError, 'invalid value for "url" when calling NewsApi.extract_news_links, the character length must be smaller than or equal to 1000.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && url !~ pattern
        fail ArgumentError, "invalid value for 'url' when calling NewsApi.extract_news_links, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/extract-news-links'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'url'] = url
      query_params[:'analyze'] = opts[:'analyze'] if !opts[:'analyze'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ExtractNewsLinks200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.extract_news_links",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#extract_news_links\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Geo Coordinates
    # Retrieve the latitude and longitude of a location name. Given this information you can fill the location-filter parameter in the news search endpoint.
    # @param location [String] The address or name of the location.
    # @param [Hash] opts the optional parameters
    # @return [GetGeoCoordinates200Response]
    def get_geo_coordinates(location, opts = {})
      data, _status_code, _headers = get_geo_coordinates_with_http_info(location, opts)
      data
    end

    # Get Geo Coordinates
    # Retrieve the latitude and longitude of a location name. Given this information you can fill the location-filter parameter in the news search endpoint.
    # @param location [String] The address or name of the location.
    # @param [Hash] opts the optional parameters
    # @return [Array<(GetGeoCoordinates200Response, Integer, Hash)>] GetGeoCoordinates200Response data, response status code and response headers
    def get_geo_coordinates_with_http_info(location, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.get_geo_coordinates ...'
      end
      # verify the required parameter 'location' is set
      if @api_client.config.client_side_validation && location.nil?
        fail ArgumentError, "Missing the required parameter 'location' when calling NewsApi.get_geo_coordinates"
      end
      if @api_client.config.client_side_validation && location.to_s.length > 1000
        fail ArgumentError, 'invalid value for "location" when calling NewsApi.get_geo_coordinates, the character length must be smaller than or equal to 1000.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && location !~ pattern
        fail ArgumentError, "invalid value for 'location' when calling NewsApi.get_geo_coordinates, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/geo-coordinates'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'location'] = location

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'GetGeoCoordinates200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.get_geo_coordinates",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#get_geo_coordinates\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # News Website to RSS Feed
    # Turn a news website into an RSS feed. Any page of a news website can be turned into an RSS feed. Provide the URL to the page and the API will return an RSS feed with the latest news from that page.
    # @param url [String] The url of the site for which an RSS feed should be created.
    # @param [Hash] opts the optional parameters
    # @option opts [Boolean] :extract_news Whether to extract the news for each link instead of just returning the link.
    # @return [Object]
    def news_website_to_rss_feed(url, opts = {})
      data, _status_code, _headers = news_website_to_rss_feed_with_http_info(url, opts)
      data
    end

    # News Website to RSS Feed
    # Turn a news website into an RSS feed. Any page of a news website can be turned into an RSS feed. Provide the URL to the page and the API will return an RSS feed with the latest news from that page.
    # @param url [String] The url of the site for which an RSS feed should be created.
    # @param [Hash] opts the optional parameters
    # @option opts [Boolean] :extract_news Whether to extract the news for each link instead of just returning the link.
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def news_website_to_rss_feed_with_http_info(url, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.news_website_to_rss_feed ...'
      end
      # verify the required parameter 'url' is set
      if @api_client.config.client_side_validation && url.nil?
        fail ArgumentError, "Missing the required parameter 'url' when calling NewsApi.news_website_to_rss_feed"
      end
      if @api_client.config.client_side_validation && url.to_s.length > 1000
        fail ArgumentError, 'invalid value for "url" when calling NewsApi.news_website_to_rss_feed, the character length must be smaller than or equal to 1000.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && url !~ pattern
        fail ArgumentError, "invalid value for 'url' when calling NewsApi.news_website_to_rss_feed, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/feed.rss'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'url'] = url
      query_params[:'extract-news'] = opts[:'extract_news'] if !opts[:'extract_news'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/xml']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.news_website_to_rss_feed",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#news_website_to_rss_feed\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve News Articles by Ids
    # Retrieve information about one or more news articles by their ids. The ids can be retrieved from the search news or top news APIs.
    # @param ids [String] A comma separated list of news ids.
    # @param [Hash] opts the optional parameters
    # @return [RetrieveNewsArticlesByIds200Response]
    def retrieve_news_articles_by_ids(ids, opts = {})
      data, _status_code, _headers = retrieve_news_articles_by_ids_with_http_info(ids, opts)
      data
    end

    # Retrieve News Articles by Ids
    # Retrieve information about one or more news articles by their ids. The ids can be retrieved from the search news or top news APIs.
    # @param ids [String] A comma separated list of news ids.
    # @param [Hash] opts the optional parameters
    # @return [Array<(RetrieveNewsArticlesByIds200Response, Integer, Hash)>] RetrieveNewsArticlesByIds200Response data, response status code and response headers
    def retrieve_news_articles_by_ids_with_http_info(ids, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.retrieve_news_articles_by_ids ...'
      end
      # verify the required parameter 'ids' is set
      if @api_client.config.client_side_validation && ids.nil?
        fail ArgumentError, "Missing the required parameter 'ids' when calling NewsApi.retrieve_news_articles_by_ids"
      end
      if @api_client.config.client_side_validation && ids.to_s.length > 10000
        fail ArgumentError, 'invalid value for "ids" when calling NewsApi.retrieve_news_articles_by_ids, the character length must be smaller than or equal to 10000.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && ids !~ pattern
        fail ArgumentError, "invalid value for 'ids' when calling NewsApi.retrieve_news_articles_by_ids, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/retrieve-news'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'ids'] = ids

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'RetrieveNewsArticlesByIds200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.retrieve_news_articles_by_ids",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#retrieve_news_articles_by_ids\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve Newspaper Front Page
    # Get the front pages of newspapers from around the world. The API provides images of the front pages of newspapers from different countries. Here's an example of some of today's newspapers:
    # @param [Hash] opts the optional parameters
    # @option opts [String] :source_country The ISO 3166 country code of the newspaper publication.
    # @option opts [String] :source_name The identifier of the publication see attached list.
    # @option opts [String] :date The date for which the front page should be retrieved. You can also go into the past, the earliest date is 2024-07-09.
    # @return [RetrieveNewspaperFrontPage200Response]
    def retrieve_newspaper_front_page(opts = {})
      data, _status_code, _headers = retrieve_newspaper_front_page_with_http_info(opts)
      data
    end

    # Retrieve Newspaper Front Page
    # Get the front pages of newspapers from around the world. The API provides images of the front pages of newspapers from different countries. Here&#39;s an example of some of today&#39;s newspapers:
    # @param [Hash] opts the optional parameters
    # @option opts [String] :source_country The ISO 3166 country code of the newspaper publication.
    # @option opts [String] :source_name The identifier of the publication see attached list.
    # @option opts [String] :date The date for which the front page should be retrieved. You can also go into the past, the earliest date is 2024-07-09.
    # @return [Array<(RetrieveNewspaperFrontPage200Response, Integer, Hash)>] RetrieveNewspaperFrontPage200Response data, response status code and response headers
    def retrieve_newspaper_front_page_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.retrieve_newspaper_front_page ...'
      end
      if @api_client.config.client_side_validation && !opts[:'source_country'].nil? && opts[:'source_country'].to_s.length > 2
        fail ArgumentError, 'invalid value for "opts[:"source_country"]" when calling NewsApi.retrieve_newspaper_front_page, the character length must be smaller than or equal to 2.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'source_country'].nil? && opts[:'source_country'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"source_country\"]' when calling NewsApi.retrieve_newspaper_front_page, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'source_name'].nil? && opts[:'source_name'].to_s.length > 100
        fail ArgumentError, 'invalid value for "opts[:"source_name"]" when calling NewsApi.retrieve_newspaper_front_page, the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'source_name'].nil? && opts[:'source_name'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"source_name\"]' when calling NewsApi.retrieve_newspaper_front_page, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'date'].nil? && opts[:'date'].to_s.length > 10
        fail ArgumentError, 'invalid value for "opts[:"date"]" when calling NewsApi.retrieve_newspaper_front_page, the character length must be smaller than or equal to 10.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'date'].nil? && opts[:'date'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"date\"]' when calling NewsApi.retrieve_newspaper_front_page, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/retrieve-front-page'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'source-country'] = opts[:'source_country'] if !opts[:'source_country'].nil?
      query_params[:'source-name'] = opts[:'source_name'] if !opts[:'source_name'].nil?
      query_params[:'date'] = opts[:'date'] if !opts[:'date'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'RetrieveNewspaperFrontPage200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.retrieve_newspaper_front_page",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#retrieve_newspaper_front_page\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Search News
    # Search and filter news by text, date, location, category, language, and more. The API returns a list of news articles matching the given criteria. Each returned article includes the title, the full text of the article, a summary, image URL, video URL, the publish date, the authors, the category, the language, the source country, and the sentiment of the article. You can set as many filtering parameters as you like, but you have to set at least one, e.g. text or language.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :text The text to match in the news content (at least 3 characters, maximum 100 characters). By default all query terms are expected, you can use an uppercase OR to search for any terms, e.g. tesla OR ford. You can also exclude terms by putting a minus sign (-) in front of the term, e.g. tesla -ford. For exact matches just put your term in quotes, e.g. \&quot;elon musk\&quot;.
    # @option opts [String] :text_match_indexes If a \&quot;text\&quot; is given to search for, you can specify where this text is searched for. Possible values are title, content, or both separated by a comma. By default, both title and content are searched.
    # @option opts [String] :source_country The ISO 3166 country code from which the news should originate.
    # @option opts [String] :language The ISO 6391 language code of the news.
    # @option opts [Float] :min_sentiment The minimal sentiment of the news in range [-1,1].
    # @option opts [Float] :max_sentiment The maximal sentiment of the news in range [-1,1].
    # @option opts [String] :earliest_publish_date The news must have been published after this date.
    # @option opts [String] :latest_publish_date The news must have been published before this date.
    # @option opts [String] :news_sources A comma-separated list of news sources from which the news should originate.
    # @option opts [String] :authors A comma-separated list of author names. Only news from any of the given authors will be returned.
    # @option opts [String] :categories A comma-separated list of categories. Only news from any of the given categories will be returned. Possible categories are politics, sports, business, technology, entertainment, health, science, lifestyle, travel, culture, education, environment, other. Please note that the filter might leave out news, especially in non-English languages. If too few results are returned, use the text parameter instead.
    # @option opts [String] :entities Filter news by entities (see semantic types).
    # @option opts [String] :location_filter Filter news by radius around a certain location. Format is \&quot;latitude,longitude,radius in kilometers\&quot;. Radius must be between 1 and 100 kilometers.
    # @option opts [String] :sort The sorting criteria (publish-time).
    # @option opts [String] :sort_direction Whether to sort ascending or descending (ASC or DESC).
    # @option opts [Integer] :offset The number of news to skip in range [0,100000]
    # @option opts [Integer] :number The number of news to return in range [1,100]
    # @return [SearchNews200Response]
    def search_news(opts = {})
      data, _status_code, _headers = search_news_with_http_info(opts)
      data
    end

    # Search News
    # Search and filter news by text, date, location, category, language, and more. The API returns a list of news articles matching the given criteria. Each returned article includes the title, the full text of the article, a summary, image URL, video URL, the publish date, the authors, the category, the language, the source country, and the sentiment of the article. You can set as many filtering parameters as you like, but you have to set at least one, e.g. text or language.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :text The text to match in the news content (at least 3 characters, maximum 100 characters). By default all query terms are expected, you can use an uppercase OR to search for any terms, e.g. tesla OR ford. You can also exclude terms by putting a minus sign (-) in front of the term, e.g. tesla -ford. For exact matches just put your term in quotes, e.g. \&quot;elon musk\&quot;.
    # @option opts [String] :text_match_indexes If a \&quot;text\&quot; is given to search for, you can specify where this text is searched for. Possible values are title, content, or both separated by a comma. By default, both title and content are searched.
    # @option opts [String] :source_country The ISO 3166 country code from which the news should originate.
    # @option opts [String] :language The ISO 6391 language code of the news.
    # @option opts [Float] :min_sentiment The minimal sentiment of the news in range [-1,1].
    # @option opts [Float] :max_sentiment The maximal sentiment of the news in range [-1,1].
    # @option opts [String] :earliest_publish_date The news must have been published after this date.
    # @option opts [String] :latest_publish_date The news must have been published before this date.
    # @option opts [String] :news_sources A comma-separated list of news sources from which the news should originate.
    # @option opts [String] :authors A comma-separated list of author names. Only news from any of the given authors will be returned.
    # @option opts [String] :categories A comma-separated list of categories. Only news from any of the given categories will be returned. Possible categories are politics, sports, business, technology, entertainment, health, science, lifestyle, travel, culture, education, environment, other. Please note that the filter might leave out news, especially in non-English languages. If too few results are returned, use the text parameter instead.
    # @option opts [String] :entities Filter news by entities (see semantic types).
    # @option opts [String] :location_filter Filter news by radius around a certain location. Format is \&quot;latitude,longitude,radius in kilometers\&quot;. Radius must be between 1 and 100 kilometers.
    # @option opts [String] :sort The sorting criteria (publish-time).
    # @option opts [String] :sort_direction Whether to sort ascending or descending (ASC or DESC).
    # @option opts [Integer] :offset The number of news to skip in range [0,100000]
    # @option opts [Integer] :number The number of news to return in range [1,100]
    # @return [Array<(SearchNews200Response, Integer, Hash)>] SearchNews200Response data, response status code and response headers
    def search_news_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.search_news ...'
      end
      if @api_client.config.client_side_validation && !opts[:'text'].nil? && opts[:'text'].to_s.length > 100
        fail ArgumentError, 'invalid value for "opts[:"text"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'text'].nil? && opts[:'text'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"text\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'text_match_indexes'].nil? && opts[:'text_match_indexes'].to_s.length > 100
        fail ArgumentError, 'invalid value for "opts[:"text_match_indexes"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'text_match_indexes'].nil? && opts[:'text_match_indexes'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"text_match_indexes\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'source_country'].nil? && opts[:'source_country'].to_s.length > 2
        fail ArgumentError, 'invalid value for "opts[:"source_country"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 2.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'source_country'].nil? && opts[:'source_country'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"source_country\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'language'].nil? && opts[:'language'].to_s.length > 2
        fail ArgumentError, 'invalid value for "opts[:"language"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 2.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'language'].nil? && opts[:'language'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"language\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'min_sentiment'].nil? && opts[:'min_sentiment'] > 1
        fail ArgumentError, 'invalid value for "opts[:"min_sentiment"]" when calling NewsApi.search_news, must be smaller than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'min_sentiment'].nil? && opts[:'min_sentiment'] < -1
        fail ArgumentError, 'invalid value for "opts[:"min_sentiment"]" when calling NewsApi.search_news, must be greater than or equal to -1.'
      end

      if @api_client.config.client_side_validation && !opts[:'max_sentiment'].nil? && opts[:'max_sentiment'] > 1
        fail ArgumentError, 'invalid value for "opts[:"max_sentiment"]" when calling NewsApi.search_news, must be smaller than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'max_sentiment'].nil? && opts[:'max_sentiment'] < -1
        fail ArgumentError, 'invalid value for "opts[:"max_sentiment"]" when calling NewsApi.search_news, must be greater than or equal to -1.'
      end

      if @api_client.config.client_side_validation && !opts[:'earliest_publish_date'].nil? && opts[:'earliest_publish_date'].to_s.length > 19
        fail ArgumentError, 'invalid value for "opts[:"earliest_publish_date"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 19.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'earliest_publish_date'].nil? && opts[:'earliest_publish_date'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"earliest_publish_date\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'latest_publish_date'].nil? && opts[:'latest_publish_date'].to_s.length > 19
        fail ArgumentError, 'invalid value for "opts[:"latest_publish_date"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 19.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'latest_publish_date'].nil? && opts[:'latest_publish_date'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"latest_publish_date\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'news_sources'].nil? && opts[:'news_sources'].to_s.length > 10000
        fail ArgumentError, 'invalid value for "opts[:"news_sources"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 10000.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'news_sources'].nil? && opts[:'news_sources'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"news_sources\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'authors'].nil? && opts[:'authors'].to_s.length > 300
        fail ArgumentError, 'invalid value for "opts[:"authors"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 300.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'authors'].nil? && opts[:'authors'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"authors\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'categories'].nil? && opts[:'categories'].to_s.length > 300
        fail ArgumentError, 'invalid value for "opts[:"categories"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 300.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'categories'].nil? && opts[:'categories'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"categories\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'entities'].nil? && opts[:'entities'].to_s.length > 10000
        fail ArgumentError, 'invalid value for "opts[:"entities"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 10000.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'entities'].nil? && opts[:'entities'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"entities\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'location_filter'].nil? && opts[:'location_filter'].to_s.length > 100
        fail ArgumentError, 'invalid value for "opts[:"location_filter"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'location_filter'].nil? && opts[:'location_filter'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"location_filter\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'sort'].nil? && opts[:'sort'].to_s.length > 100
        fail ArgumentError, 'invalid value for "opts[:"sort"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'sort'].nil? && opts[:'sort'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"sort\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'sort_direction'].nil? && opts[:'sort_direction'].to_s.length > 4
        fail ArgumentError, 'invalid value for "opts[:"sort_direction"]" when calling NewsApi.search_news, the character length must be smaller than or equal to 4.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'sort_direction'].nil? && opts[:'sort_direction'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"sort_direction\"]' when calling NewsApi.search_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'offset'].nil? && opts[:'offset'] > 10000
        fail ArgumentError, 'invalid value for "opts[:"offset"]" when calling NewsApi.search_news, must be smaller than or equal to 10000.'
      end

      if @api_client.config.client_side_validation && !opts[:'offset'].nil? && opts[:'offset'] < 0
        fail ArgumentError, 'invalid value for "opts[:"offset"]" when calling NewsApi.search_news, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'number'].nil? && opts[:'number'] > 100
        fail ArgumentError, 'invalid value for "opts[:"number"]" when calling NewsApi.search_news, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'number'].nil? && opts[:'number'] < 1
        fail ArgumentError, 'invalid value for "opts[:"number"]" when calling NewsApi.search_news, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/search-news'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'text'] = opts[:'text'] if !opts[:'text'].nil?
      query_params[:'text-match-indexes'] = opts[:'text_match_indexes'] if !opts[:'text_match_indexes'].nil?
      query_params[:'source-country'] = opts[:'source_country'] if !opts[:'source_country'].nil?
      query_params[:'language'] = opts[:'language'] if !opts[:'language'].nil?
      query_params[:'min-sentiment'] = opts[:'min_sentiment'] if !opts[:'min_sentiment'].nil?
      query_params[:'max-sentiment'] = opts[:'max_sentiment'] if !opts[:'max_sentiment'].nil?
      query_params[:'earliest-publish-date'] = opts[:'earliest_publish_date'] if !opts[:'earliest_publish_date'].nil?
      query_params[:'latest-publish-date'] = opts[:'latest_publish_date'] if !opts[:'latest_publish_date'].nil?
      query_params[:'news-sources'] = opts[:'news_sources'] if !opts[:'news_sources'].nil?
      query_params[:'authors'] = opts[:'authors'] if !opts[:'authors'].nil?
      query_params[:'categories'] = opts[:'categories'] if !opts[:'categories'].nil?
      query_params[:'entities'] = opts[:'entities'] if !opts[:'entities'].nil?
      query_params[:'location-filter'] = opts[:'location_filter'] if !opts[:'location_filter'].nil?
      query_params[:'sort'] = opts[:'sort'] if !opts[:'sort'].nil?
      query_params[:'sort-direction'] = opts[:'sort_direction'] if !opts[:'sort_direction'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?
      query_params[:'number'] = opts[:'number'] if !opts[:'number'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SearchNews200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.search_news",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#search_news\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Search News Sources
    # Search whether a news source is being monitored by the World News API. This API is useful if you want to know if a specific news source is available in the API.
    # @param name [String] The (partial) name of the source.
    # @param [Hash] opts the optional parameters
    # @return [SearchNewsSources200Response]
    def search_news_sources(name, opts = {})
      data, _status_code, _headers = search_news_sources_with_http_info(name, opts)
      data
    end

    # Search News Sources
    # Search whether a news source is being monitored by the World News API. This API is useful if you want to know if a specific news source is available in the API.
    # @param name [String] The (partial) name of the source.
    # @param [Hash] opts the optional parameters
    # @return [Array<(SearchNewsSources200Response, Integer, Hash)>] SearchNewsSources200Response data, response status code and response headers
    def search_news_sources_with_http_info(name, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.search_news_sources ...'
      end
      # verify the required parameter 'name' is set
      if @api_client.config.client_side_validation && name.nil?
        fail ArgumentError, "Missing the required parameter 'name' when calling NewsApi.search_news_sources"
      end
      if @api_client.config.client_side_validation && name.to_s.length > 1000
        fail ArgumentError, 'invalid value for "name" when calling NewsApi.search_news_sources, the character length must be smaller than or equal to 1000.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && name !~ pattern
        fail ArgumentError, "invalid value for 'name' when calling NewsApi.search_news_sources, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/search-news-sources'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'name'] = name

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SearchNewsSources200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.search_news_sources",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#search_news_sources\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Top News
    # Get the top news from a country in a language for a specific date. The top news are clustered from multiple sources in the given country. The more news in a cluster the higher the cluster is ranked.
    # @param source_country [String] The ISO 3166 country code of the country for which top news should be retrieved.
    # @param language [String] The ISO 6391 language code of the top news. The language must be one spoken in the source-country.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :date The date for which the top news should be retrieved. If no date is given, the current day is assumed.
    # @option opts [Boolean] :headlines_only Whether to only return basic information such as id, title, and url of the news.
    # @return [TopNews200Response]
    def top_news(source_country, language, opts = {})
      data, _status_code, _headers = top_news_with_http_info(source_country, language, opts)
      data
    end

    # Top News
    # Get the top news from a country in a language for a specific date. The top news are clustered from multiple sources in the given country. The more news in a cluster the higher the cluster is ranked.
    # @param source_country [String] The ISO 3166 country code of the country for which top news should be retrieved.
    # @param language [String] The ISO 6391 language code of the top news. The language must be one spoken in the source-country.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :date The date for which the top news should be retrieved. If no date is given, the current day is assumed.
    # @option opts [Boolean] :headlines_only Whether to only return basic information such as id, title, and url of the news.
    # @return [Array<(TopNews200Response, Integer, Hash)>] TopNews200Response data, response status code and response headers
    def top_news_with_http_info(source_country, language, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NewsApi.top_news ...'
      end
      # verify the required parameter 'source_country' is set
      if @api_client.config.client_side_validation && source_country.nil?
        fail ArgumentError, "Missing the required parameter 'source_country' when calling NewsApi.top_news"
      end
      if @api_client.config.client_side_validation && source_country.to_s.length > 2
        fail ArgumentError, 'invalid value for "source_country" when calling NewsApi.top_news, the character length must be smaller than or equal to 2.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && source_country !~ pattern
        fail ArgumentError, "invalid value for 'source_country' when calling NewsApi.top_news, must conform to the pattern #{pattern}."
      end

      # verify the required parameter 'language' is set
      if @api_client.config.client_side_validation && language.nil?
        fail ArgumentError, "Missing the required parameter 'language' when calling NewsApi.top_news"
      end
      if @api_client.config.client_side_validation && language.to_s.length > 2
        fail ArgumentError, 'invalid value for "language" when calling NewsApi.top_news, the character length must be smaller than or equal to 2.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && language !~ pattern
        fail ArgumentError, "invalid value for 'language' when calling NewsApi.top_news, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'date'].nil? && opts[:'date'].to_s.length > 10
        fail ArgumentError, 'invalid value for "opts[:"date"]" when calling NewsApi.top_news, the character length must be smaller than or equal to 10.'
      end

      pattern = Regexp.new(/./)
      if @api_client.config.client_side_validation && !opts[:'date'].nil? && opts[:'date'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"date\"]' when calling NewsApi.top_news, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/top-news'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'source-country'] = source_country
      query_params[:'language'] = language
      query_params[:'date'] = opts[:'date'] if !opts[:'date'].nil?
      query_params[:'headlines-only'] = opts[:'headlines_only'] if !opts[:'headlines_only'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TopNews200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKey', 'headerApiKey']

      new_options = opts.merge(
        :operation => :"NewsApi.top_news",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NewsApi#top_news\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
