=begin
#World News API

#The world's news wrapped into a single API.

The version of the OpenAPI document: 2.2.0
Contact: mail@worldnewsapi.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SearchNewsSources200ResponseSourcesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SearchNewsSources200ResponseSourcesInner do
  let(:instance) { OpenapiClient::SearchNewsSources200ResponseSourcesInner.new }

  describe 'test an instance of SearchNewsSources200ResponseSourcesInner' do
    it 'should create an instance of SearchNewsSources200ResponseSourcesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SearchNewsSources200ResponseSourcesInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "language"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
