/*
 * World News API
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: mail@worldnewsapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.worldnewsapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.worldnewsapi.client.model.TopNews200ResponseTopNewsInnerNewsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TopNews200ResponseTopNewsInner
 */
public class TopNews200ResponseTopNewsInnerTest {
    private final TopNews200ResponseTopNewsInner model = new TopNews200ResponseTopNewsInner();

    /**
     * Model tests for TopNews200ResponseTopNewsInner
     */
    @Test
    public void testTopNews200ResponseTopNewsInner() {
        // TODO: test TopNews200ResponseTopNewsInner
    }

    /**
     * Test the property 'news'
     */
    @Test
    public void newsTest() {
        // TODO: test news
    }

}
