/**
 * World News API
 *
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@worldnewsapi.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.worldnewsapi.client.model

import com.worldnewsapi.client.model.InlineResponse200News

import com.squareup.moshi.Json

/**
 * 
 *
 * @param offset 
 * @param number 
 * @param available 
 * @param news 
 */

data class InlineResponse200 (

    @Json(name = "offset")
    val offset: kotlin.Int,

    @Json(name = "number")
    val number: kotlin.Int,

    @Json(name = "available")
    val available: kotlin.Int,

    @Json(name = "news")
    val news: kotlin.collections.List<InlineResponse200News>

)

