--[[
  World News API

  The world's news wrapped into a single API.

  The version of the OpenAPI document: 1.0
  Contact: mail@worldnewsapi.com
  Generated by: https://openapi-generator.tech
]]

-- inline_response_200_1 class
local inline_response_200_1 = {}
local inline_response_200_1_mt = {
	__name = "inline_response_200_1";
	__index = inline_response_200_1;
}

local function cast_inline_response_200_1(t)
	return setmetatable(t, inline_response_200_1_mt)
end

local function new_inline_response_200_1(title, text, url, image, author, language, source_country, sentiment)
	return cast_inline_response_200_1({
		["title"] = title;
		["text"] = text;
		["url"] = url;
		["image"] = image;
		["author"] = author;
		["language"] = language;
		["source_country"] = source_country;
		["sentiment"] = sentiment;
	})
end

return {
	cast = cast_inline_response_200_1;
	new = new_inline_response_200_1;
}
