/**
 * World News API
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: mail@worldnewsapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchNewsSources_200_response_sources_inner.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISearchNewsSources_200_response_sources_inner::OAISearchNewsSources_200_response_sources_inner(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISearchNewsSources_200_response_sources_inner::OAISearchNewsSources_200_response_sources_inner() {
    this->initializeModel();
}

OAISearchNewsSources_200_response_sources_inner::~OAISearchNewsSources_200_response_sources_inner() {}

void OAISearchNewsSources_200_response_sources_inner::initializeModel() {

    m_name_isSet = false;
    m_name_isValid = false;

    m_url_isSet = false;
    m_url_isValid = false;

    m_language_isSet = false;
    m_language_isValid = false;
}

void OAISearchNewsSources_200_response_sources_inner::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchNewsSources_200_response_sources_inner::fromJsonObject(QJsonObject json) {

    m_name_isValid = ::OpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_url_isValid = ::OpenAPI::fromJsonValue(m_url, json[QString("url")]);
    m_url_isSet = !json[QString("url")].isNull() && m_url_isValid;

    m_language_isValid = ::OpenAPI::fromJsonValue(m_language, json[QString("language")]);
    m_language_isSet = !json[QString("language")].isNull() && m_language_isValid;
}

QString OAISearchNewsSources_200_response_sources_inner::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchNewsSources_200_response_sources_inner::asJsonObject() const {
    QJsonObject obj;
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(m_name));
    }
    if (m_url_isSet) {
        obj.insert(QString("url"), ::OpenAPI::toJsonValue(m_url));
    }
    if (m_language_isSet) {
        obj.insert(QString("language"), ::OpenAPI::toJsonValue(m_language));
    }
    return obj;
}

QString OAISearchNewsSources_200_response_sources_inner::getName() const {
    return m_name;
}
void OAISearchNewsSources_200_response_sources_inner::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool OAISearchNewsSources_200_response_sources_inner::is_name_Set() const{
    return m_name_isSet;
}

bool OAISearchNewsSources_200_response_sources_inner::is_name_Valid() const{
    return m_name_isValid;
}

QString OAISearchNewsSources_200_response_sources_inner::getUrl() const {
    return m_url;
}
void OAISearchNewsSources_200_response_sources_inner::setUrl(const QString &url) {
    m_url = url;
    m_url_isSet = true;
}

bool OAISearchNewsSources_200_response_sources_inner::is_url_Set() const{
    return m_url_isSet;
}

bool OAISearchNewsSources_200_response_sources_inner::is_url_Valid() const{
    return m_url_isValid;
}

QString OAISearchNewsSources_200_response_sources_inner::getLanguage() const {
    return m_language;
}
void OAISearchNewsSources_200_response_sources_inner::setLanguage(const QString &language) {
    m_language = language;
    m_language_isSet = true;
}

bool OAISearchNewsSources_200_response_sources_inner::is_language_Set() const{
    return m_language_isSet;
}

bool OAISearchNewsSources_200_response_sources_inner::is_language_Valid() const{
    return m_language_isValid;
}

bool OAISearchNewsSources_200_response_sources_inner::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_url_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_language_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchNewsSources_200_response_sources_inner::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
