/**
 * World News API
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: mail@worldnewsapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITopNews_200_response_top_news_inner_news_inner.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAITopNews_200_response_top_news_inner_news_inner::OAITopNews_200_response_top_news_inner_news_inner(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAITopNews_200_response_top_news_inner_news_inner::OAITopNews_200_response_top_news_inner_news_inner() {
    this->initializeModel();
}

OAITopNews_200_response_top_news_inner_news_inner::~OAITopNews_200_response_top_news_inner_news_inner() {}

void OAITopNews_200_response_top_news_inner_news_inner::initializeModel() {

    m_summary_isSet = false;
    m_summary_isValid = false;

    m_image_isSet = false;
    m_image_isValid = false;

    m_author_isSet = false;
    m_author_isValid = false;

    m_id_isSet = false;
    m_id_isValid = false;

    m_text_isSet = false;
    m_text_isValid = false;

    m_title_isSet = false;
    m_title_isValid = false;

    m_publish_date_isSet = false;
    m_publish_date_isValid = false;

    m_url_isSet = false;
    m_url_isValid = false;

    m_authors_isSet = false;
    m_authors_isValid = false;
}

void OAITopNews_200_response_top_news_inner_news_inner::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAITopNews_200_response_top_news_inner_news_inner::fromJsonObject(QJsonObject json) {

    m_summary_isValid = ::OpenAPI::fromJsonValue(m_summary, json[QString("summary")]);
    m_summary_isSet = !json[QString("summary")].isNull() && m_summary_isValid;

    m_image_isValid = ::OpenAPI::fromJsonValue(m_image, json[QString("image")]);
    m_image_isSet = !json[QString("image")].isNull() && m_image_isValid;

    m_author_isValid = ::OpenAPI::fromJsonValue(m_author, json[QString("author")]);
    m_author_isSet = !json[QString("author")].isNull() && m_author_isValid;

    m_id_isValid = ::OpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_text_isValid = ::OpenAPI::fromJsonValue(m_text, json[QString("text")]);
    m_text_isSet = !json[QString("text")].isNull() && m_text_isValid;

    m_title_isValid = ::OpenAPI::fromJsonValue(m_title, json[QString("title")]);
    m_title_isSet = !json[QString("title")].isNull() && m_title_isValid;

    m_publish_date_isValid = ::OpenAPI::fromJsonValue(m_publish_date, json[QString("publish_date")]);
    m_publish_date_isSet = !json[QString("publish_date")].isNull() && m_publish_date_isValid;

    m_url_isValid = ::OpenAPI::fromJsonValue(m_url, json[QString("url")]);
    m_url_isSet = !json[QString("url")].isNull() && m_url_isValid;

    m_authors_isValid = ::OpenAPI::fromJsonValue(m_authors, json[QString("authors")]);
    m_authors_isSet = !json[QString("authors")].isNull() && m_authors_isValid;
}

QString OAITopNews_200_response_top_news_inner_news_inner::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAITopNews_200_response_top_news_inner_news_inner::asJsonObject() const {
    QJsonObject obj;
    if (m_summary_isSet) {
        obj.insert(QString("summary"), ::OpenAPI::toJsonValue(m_summary));
    }
    if (m_image_isSet) {
        obj.insert(QString("image"), ::OpenAPI::toJsonValue(m_image));
    }
    if (m_author_isSet) {
        obj.insert(QString("author"), ::OpenAPI::toJsonValue(m_author));
    }
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(m_id));
    }
    if (m_text_isSet) {
        obj.insert(QString("text"), ::OpenAPI::toJsonValue(m_text));
    }
    if (m_title_isSet) {
        obj.insert(QString("title"), ::OpenAPI::toJsonValue(m_title));
    }
    if (m_publish_date_isSet) {
        obj.insert(QString("publish_date"), ::OpenAPI::toJsonValue(m_publish_date));
    }
    if (m_url_isSet) {
        obj.insert(QString("url"), ::OpenAPI::toJsonValue(m_url));
    }
    if (m_authors.size() > 0) {
        obj.insert(QString("authors"), ::OpenAPI::toJsonValue(m_authors));
    }
    return obj;
}

QString OAITopNews_200_response_top_news_inner_news_inner::getSummary() const {
    return m_summary;
}
void OAITopNews_200_response_top_news_inner_news_inner::setSummary(const QString &summary) {
    m_summary = summary;
    m_summary_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_summary_Set() const{
    return m_summary_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_summary_Valid() const{
    return m_summary_isValid;
}

QString OAITopNews_200_response_top_news_inner_news_inner::getImage() const {
    return m_image;
}
void OAITopNews_200_response_top_news_inner_news_inner::setImage(const QString &image) {
    m_image = image;
    m_image_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_image_Set() const{
    return m_image_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_image_Valid() const{
    return m_image_isValid;
}

QString OAITopNews_200_response_top_news_inner_news_inner::getAuthor() const {
    return m_author;
}
void OAITopNews_200_response_top_news_inner_news_inner::setAuthor(const QString &author) {
    m_author = author;
    m_author_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_author_Set() const{
    return m_author_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_author_Valid() const{
    return m_author_isValid;
}

qint32 OAITopNews_200_response_top_news_inner_news_inner::getId() const {
    return m_id;
}
void OAITopNews_200_response_top_news_inner_news_inner::setId(const qint32 &id) {
    m_id = id;
    m_id_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_id_Set() const{
    return m_id_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_id_Valid() const{
    return m_id_isValid;
}

QString OAITopNews_200_response_top_news_inner_news_inner::getText() const {
    return m_text;
}
void OAITopNews_200_response_top_news_inner_news_inner::setText(const QString &text) {
    m_text = text;
    m_text_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_text_Set() const{
    return m_text_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_text_Valid() const{
    return m_text_isValid;
}

QString OAITopNews_200_response_top_news_inner_news_inner::getTitle() const {
    return m_title;
}
void OAITopNews_200_response_top_news_inner_news_inner::setTitle(const QString &title) {
    m_title = title;
    m_title_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_title_Set() const{
    return m_title_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_title_Valid() const{
    return m_title_isValid;
}

QString OAITopNews_200_response_top_news_inner_news_inner::getPublishDate() const {
    return m_publish_date;
}
void OAITopNews_200_response_top_news_inner_news_inner::setPublishDate(const QString &publish_date) {
    m_publish_date = publish_date;
    m_publish_date_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_publish_date_Set() const{
    return m_publish_date_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_publish_date_Valid() const{
    return m_publish_date_isValid;
}

QString OAITopNews_200_response_top_news_inner_news_inner::getUrl() const {
    return m_url;
}
void OAITopNews_200_response_top_news_inner_news_inner::setUrl(const QString &url) {
    m_url = url;
    m_url_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_url_Set() const{
    return m_url_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_url_Valid() const{
    return m_url_isValid;
}

QList<QString> OAITopNews_200_response_top_news_inner_news_inner::getAuthors() const {
    return m_authors;
}
void OAITopNews_200_response_top_news_inner_news_inner::setAuthors(const QList<QString> &authors) {
    m_authors = authors;
    m_authors_isSet = true;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_authors_Set() const{
    return m_authors_isSet;
}

bool OAITopNews_200_response_top_news_inner_news_inner::is_authors_Valid() const{
    return m_authors_isValid;
}

bool OAITopNews_200_response_top_news_inner_news_inner::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_summary_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_image_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_author_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_text_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_title_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_publish_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_url_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_authors.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAITopNews_200_response_top_news_inner_news_inner::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
