/*
 * World News API
 *
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: mail@worldnewsapi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveNewspaperFrontPage200Response {
    #[serde(rename = "front_page", skip_serializing_if = "Option::is_none")]
    pub front_page: Option<Box<models::RetrieveNewspaperFrontPage200ResponseFrontPage>>,
}

impl RetrieveNewspaperFrontPage200Response {
    pub fn new() -> RetrieveNewspaperFrontPage200Response {
        RetrieveNewspaperFrontPage200Response {
            front_page: None,
        }
    }
}

