/*
 * World News API
 *
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 1.1
 * Contact: mail@worldnewsapi.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchNewsResponse {
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "available")]
    pub available: i32,
    #[serde(rename = "news")]
    pub news: Vec<crate::models::NewsArticle>,
}

impl SearchNewsResponse {
    pub fn new(offset: i32, number: i32, available: i32, news: Vec<crate::models::NewsArticle>) -> SearchNewsResponse {
        SearchNewsResponse {
            offset,
            number,
            available,
            news,
        }
    }
}


