/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package worldnewsapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import worldnewsapi.models.RetrieveNewspaperFrontPage200ResponseFrontPage

class RetrieveNewspaperFrontPage200ResponseFrontPageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RetrieveNewspaperFrontPage200ResponseFrontPage
        //val modelInstance = RetrieveNewspaperFrontPage200ResponseFrontPage()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `language`
        should("test language") {
            // uncomment below to test the property
            //modelInstance.language shouldBe ("TODO")
        }

    }
}
