=begin
#World News API

#The world's news wrapped into a single API.

The version of the OpenAPI document: 1.1
Contact: mail@worldnewsapi.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::NewsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NewsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::NewsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NewsApi' do
    it 'should create an instance of NewsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::NewsApi)
    end
  end

  # unit tests for extract_news
  # Extract News
  # Extract a news entry from a news site.
  # @param url The url of the news.
  # @param analyze Whether to analyze the news (extract entities etc.)
  # @param [Hash] opts the optional parameters
  # @return [ExtractNewsResponse]
  describe 'extract_news test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for extract_news_links
  # Extract News Links
  # Extract a news links from a news website. 
  # @param url The url from which links should be extracted.
  # @param api_key Your API key.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :prefix The prefix the news links must start with.
  # @option opts [Boolean] :sub_domain Whether to include links to news on sub-domains.
  # @return [ExtractLinksResponse]
  describe 'extract_news_links test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for geo_coordinates
  # Get Geo Coordinates
  # Get the geo coordinates for a location. The location can be an exact address but also just the name of a city or country.
  # @param location The address or name of the location, e.g. Tokyo, Japan.
  # @param [Hash] opts the optional parameters
  # @return [GeoCoordinatesResponse]
  describe 'geo_coordinates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for news_website_to_rss_feed
  # News Website to RSS Feed
  # Turn a news website into an RSS feed. Any page of a news website can be turned into an RSS feed. Provide the URL to the page and the API will return an RSS feed with the latest news from that page. 
  # @param url The url from which links should be extracted.
  # @param api_key Your API key.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :extract_news Whether extract news and add information such as description, publish date, and image to each item.
  # @return [Object]
  describe 'news_website_to_rss_feed test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_news
  # Search News
  # Search for news.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :text The text to match in the news content.
  # @option opts [String] :source_countries A comma-separated list of ISO 3166 country codes from which the news should originate, e.g. gb,us.
  # @option opts [String] :language The ISO 6391 language code of the news, e.g. \&quot;en\&quot; for English.
  # @option opts [Float] :min_sentiment The minimal sentiment of the news in range [-1,1].
  # @option opts [Float] :max_sentiment The maximal sentiment of the news in range [-1,1].
  # @option opts [String] :earliest_publish_date The news must have been published after this date.
  # @option opts [String] :latest_publish_date The news must have been published before this date.
  # @option opts [String] :news_sources A comma-separated list of news sources from which the news should originate, e.g. https://www.bbc.co.uk
  # @option opts [String] :authors A comma-separated list of author names. Only news from any of the given authors will be returned.
  # @option opts [String] :entities Filter news by entities, e.g. ORG:Tesla.
  # @option opts [String] :location_filter Filter news by radius around a certain location. Format is \&quot;latitude,longitude,radius in kilometers\&quot;, e.g. 51.050407, 13.737262, 100
  # @option opts [Integer] :offset The number of news to skip in range [0,1000]
  # @option opts [Integer] :number The number of news to return in range [1,100]
  # @option opts [String] :sort The sorting criteria.
  # @option opts [String] :sort_direction Whether to sort ascending or descending.
  # @return [SearchNewsResponse]
  describe 'search_news test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
