--[[
  World News API

  The world's news wrapped into a single API.

  The version of the OpenAPI document: 2.2.0
  Contact: mail@worldnewsapi.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for worldnewsapi.model.get_geo_coordinates_200_response
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("get_geo_coordinates_200_response", function()
  local worldnewsapi_get_geo_coordinates_200_response = require "worldnewsapi.model.get_geo_coordinates_200_response"

  -- unit tests for the property 'latitude'
  describe("property latitude test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'longitude'
  describe("property longitude test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'city'
  describe("property city test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
