/**
 * World News API
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@worldnewsapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2002 model module.
 * @module com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse2002
 * @version 1.0
 */
class InlineResponse2002 {
    /**
     * Constructs a new <code>InlineResponse2002</code>.
     * @alias module:com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse2002
     * @param latitude {Number} 
     * @param longitude {Number} 
     */
    constructor(latitude, longitude) { 
        
        InlineResponse2002.initialize(this, latitude, longitude);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, latitude, longitude) { 
        obj['latitude'] = latitude;
        obj['longitude'] = longitude;
    }

    /**
     * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse2002} obj Optional instance to populate.
     * @return {module:com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2002();

            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} latitude
 */
InlineResponse2002.prototype['latitude'] = undefined;

/**
 * @member {Number} longitude
 */
InlineResponse2002.prototype['longitude'] = undefined;

/**
 * @member {String} city
 */
InlineResponse2002.prototype['city'] = undefined;






export default InlineResponse2002;

