/**
 * World News API
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@worldnewsapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse200News from './InlineResponse200News';

/**
 * The InlineResponse200 model module.
 * @module com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse200
 * @version 1.0
 */
class InlineResponse200 {
    /**
     * Constructs a new <code>InlineResponse200</code>.
     * @alias module:com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse200
     * @param offset {Number} 
     * @param number {Number} 
     * @param available {Number} 
     * @param news {Array.<module:com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse200News>} 
     */
    constructor(offset, number, available, news) { 
        
        InlineResponse200.initialize(this, offset, number, available, news);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, offset, number, available, news) { 
        obj['offset'] = offset;
        obj['number'] = number;
        obj['available'] = available;
        obj['news'] = news;
    }

    /**
     * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse200} obj Optional instance to populate.
     * @return {module:com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200();

            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'Number');
            }
            if (data.hasOwnProperty('news')) {
                obj['news'] = ApiClient.convertToType(data['news'], [InlineResponse200News]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} offset
 */
InlineResponse200.prototype['offset'] = undefined;

/**
 * @member {Number} number
 */
InlineResponse200.prototype['number'] = undefined;

/**
 * @member {Number} available
 */
InlineResponse200.prototype['available'] = undefined;

/**
 * @member {Array.<module:com.worldnewsapi.client/com.worldnewsapi.client.model/InlineResponse200News>} news
 */
InlineResponse200.prototype['news'] = undefined;






export default InlineResponse200;

