# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WorldNewsAPI.Model.RetrieveNewsArticlesByIds200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :news
  ]

  @type t :: %__MODULE__{
    :news => [WorldNewsAPI.Model.RetrieveNewsArticlesByIds200ResponseNewsInner.t] | nil
  }

  alias WorldNewsAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:news, :list, WorldNewsAPI.Model.RetrieveNewsArticlesByIds200ResponseNewsInner)
  end
end

