# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WorldNewsAPI.Model.SearchNewsSources200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :available,
    :sources
  ]

  @type t :: %__MODULE__{
    :available => integer() | nil,
    :sources => [WorldNewsAPI.Model.SearchNewsSources200ResponseSourcesInner.t] | nil
  }

  alias WorldNewsAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:sources, :list, WorldNewsAPI.Model.SearchNewsSources200ResponseSourcesInner)
  end
end

