/**
 * World News API
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@worldnewsapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_2.h
 *
 * 
 */

#ifndef OAIInline_response_200_2_H
#define OAIInline_response_200_2_H

#include <QJsonObject>

#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIInline_response_200_2 : public OAIObject {
public:
    OAIInline_response_200_2();
    OAIInline_response_200_2(QString json);
    ~OAIInline_response_200_2() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<QString> getNewsLinks() const;
    void setNewsLinks(const QList<QString> &news_links);
    bool is_news_links_Set() const;
    bool is_news_links_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<QString> news_links;
    bool m_news_links_isSet;
    bool m_news_links_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIInline_response_200_2)

#endif // OAIInline_response_200_2_H
