/**
 * World News API
 * The world's news wrapped into a single API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@worldnewsapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIInline_response_200_3.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIInline_response_200_3::OAIInline_response_200_3(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIInline_response_200_3::OAIInline_response_200_3() {
    this->initializeModel();
}

OAIInline_response_200_3::~OAIInline_response_200_3() {}

void OAIInline_response_200_3::initializeModel() {

    m_latitude_isSet = false;
    m_latitude_isValid = false;

    m_longitude_isSet = false;
    m_longitude_isValid = false;

    m_city_isSet = false;
    m_city_isValid = false;
}

void OAIInline_response_200_3::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIInline_response_200_3::fromJsonObject(QJsonObject json) {

    m_latitude_isValid = ::OpenAPI::fromJsonValue(latitude, json[QString("latitude")]);
    m_latitude_isSet = !json[QString("latitude")].isNull() && m_latitude_isValid;

    m_longitude_isValid = ::OpenAPI::fromJsonValue(longitude, json[QString("longitude")]);
    m_longitude_isSet = !json[QString("longitude")].isNull() && m_longitude_isValid;

    m_city_isValid = ::OpenAPI::fromJsonValue(city, json[QString("city")]);
    m_city_isSet = !json[QString("city")].isNull() && m_city_isValid;
}

QString OAIInline_response_200_3::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIInline_response_200_3::asJsonObject() const {
    QJsonObject obj;
    if (m_latitude_isSet) {
        obj.insert(QString("latitude"), ::OpenAPI::toJsonValue(latitude));
    }
    if (m_longitude_isSet) {
        obj.insert(QString("longitude"), ::OpenAPI::toJsonValue(longitude));
    }
    if (m_city_isSet) {
        obj.insert(QString("city"), ::OpenAPI::toJsonValue(city));
    }
    return obj;
}

double OAIInline_response_200_3::getLatitude() const {
    return latitude;
}
void OAIInline_response_200_3::setLatitude(const double &latitude) {
    this->latitude = latitude;
    this->m_latitude_isSet = true;
}

bool OAIInline_response_200_3::is_latitude_Set() const{
    return m_latitude_isSet;
}

bool OAIInline_response_200_3::is_latitude_Valid() const{
    return m_latitude_isValid;
}

double OAIInline_response_200_3::getLongitude() const {
    return longitude;
}
void OAIInline_response_200_3::setLongitude(const double &longitude) {
    this->longitude = longitude;
    this->m_longitude_isSet = true;
}

bool OAIInline_response_200_3::is_longitude_Set() const{
    return m_longitude_isSet;
}

bool OAIInline_response_200_3::is_longitude_Valid() const{
    return m_longitude_isValid;
}

QString OAIInline_response_200_3::getCity() const {
    return city;
}
void OAIInline_response_200_3::setCity(const QString &city) {
    this->city = city;
    this->m_city_isSet = true;
}

bool OAIInline_response_200_3::is_city_Set() const{
    return m_city_isSet;
}

bool OAIInline_response_200_3::is_city_Valid() const{
    return m_city_isValid;
}

bool OAIInline_response_200_3::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_latitude_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_longitude_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_city_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIInline_response_200_3::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_latitude_isValid && m_longitude_isValid && true;
}

} // namespace OpenAPI
